# kubernetes/cybermanager-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cybermanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cybermanager
  template:
    metadata:
      labels:
        app: cybermanager
    spec:
      containers:
      - name: cybermanager
        # 1. ON UTILISE TON IMAGE LOCALE V2
        image: cybermanager:v3
        # 2. IMPORTANT : On interdit Ã  K8s de chercher sur Internet
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        # 3. ON UTILISE LA VARIABLE EXACTE QUE PYTHON ATTEND
        - name: DATABASE_URL
          value: "mysql+pymysql://root:password@mysql/cybermanager_db"
        - name: SECRET_KEY
          value: "cle-secrete-production"
