# kubernetes/cybermanager-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cybermanager-service
spec:
  type: NodePort # Expose le service sur un port de la machine Minikube
  ports:
    - port: 5000 # Port interne au cluster
      targetPort: 5000 # Port du conteneur
  selector:
    app: cybermanager # Cible les pods de votre application