# kubernetes/mysql-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim # On demande du stockage persistant
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce # Le volume peut être monté en lecture/écriture par un seul nœud
  resources:
    requests:
      storage: 1Gi # On demande 1 Gigaoctet de stockage